version: '3.7'
services:
  shell:
    build: ./zappa-shell
    links:
      - database
    volumes:
      - .:/var/task
      - ~/.aws/:/root/.aws:ro
  database:
    image: postgres:10.7
    ports:
      - "5432:5432"
    volumes:
      - .:/code
      - postgresql-volume:/var/lib/postgresql/data
volumes:
  postgresql-volume:
