version: '3.4'
services:
  backend:
    image: lambci/lambda:build-python3.8
    links:
      - database
    volumes:
      - .:/var/task
  database:
    image: database:10.7
    ports:
    - "5432:5432"
    volumes:
    - .:/code
    - postgresql-volume:/var/lib/postgresql/data
volumes:
  postgresql-volume:
